# -*- coding: utf-8 -*-
"""talentsprint_code.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LcdiRoLkzUmr8_cGwW7O2h9nNwm2AObn
"""

# from turtle import title
import re
import scrapy
import datetime


class TalentspSpider(scrapy.Spider):
    name = 'talentsp'
    start_urls = ['https://talentsprint.com/programs.dpl#program=.all']

    def parse(self, response):
        url = 'https://talentsprint.com/programs.dpl#program=.all'
        yield scrapy.Request(url=url, callback=self.parse_page)

# #//*[@id="technologies"]/div[2]/div/div[2]/div/div/div[1]/div/a/div/div[1]/p[2]

    def parse_page(self, response):
        url = 'https://talentsprint.com/programs.dpl#program=.all'
        
        for t,s,d,i in zip(response.css('p.program-title').getall(), response.css('div.bottomcta li::text').getall(), response.css('p.duration').getall(),response.css('div.program-card-inner a::attr(href)').getall()):
            title = t.replace('<p class=\"program-title\">','').replace('                                    ','').replace('\r','').replace('\n','').replace('<br>','').replace('</p>','').replace('                                ','').replace('<span>','').replace('</span>','')
            if 'starts' in s or 'Starts' in s or 'Applications' in s:
                sd = s.replace('Starts in ','').replace('Batch 20 starts in ','').replace('Batch 8 starts in','').replace(' O','O').replace('  S','S').replace(' ','-')
                if sd != 'Applications-Closed' and sd != 'Applications-closed' and sd != '-Applications-closed':
                    start_date = datetime.datetime.strptime(sd, '%B-%Y')
            else:
                sd = ''
            for j in d.split('<span>'):
                if 'Month' in j or 'Months' in j:
                    dur = j.replace('<p class=\"duration\">','').replace('</span>','').replace('\r','').replace('\n','').replace('.','').replace('                                    ','').replace('                      ','')
            yield scrapy.Request(url=i, callback=self.parse_info, cb_kwargs={'title':title, 'start_date':start_date, 'duration':dur})

    def parse_info(self, response, title, start_date, duration):
        title1 = title
        ## Description
        description = ''
        desc = response.css('div.col-md-8 div.col-md-12').getall()
        for i in desc:
            re_description1 = re.sub('<(.*?)>','',i)
            re_description2 = re.sub('\s\s','',re_description1)
            re_description3 = re.sub('</(.*?)>','',re_description2)
            re_description = re_description3.replace('\t','').replace('\n','').replace('\r','')
            description += '<p>' + re_description + '</p>'

        if description == '':
            desc = response.css('div.col-md-8 p::text').getall()
            for i in desc:
                re_description1 = re.sub('<(.*?)>','',i)
                re_description2 = re.sub('\s\s','',re_description1)
                re_description3 = re.sub('</(.*?)>','',re_description2)
                re_description = re_description3.replace('\t','').replace('\n','').replace('\r','')
                description += '<p>' + re_description + '</p>'
        
        if description == '':
            desc = response.css('div.col-md-12 div.secure-box p::text').getall()
            for i in desc:
                re_description1 = re.sub('<(.*?)>','',i)
                re_description2 = re.sub('\s\s','',re_description1)
                re_description3 = re.sub('</(.*?)>','',re_description2)
                re_description = re_description3.replace('\t','').replace('\n','').replace('\r','')
                description += '<p>' + re_description + '</p>'
        
        if description == '':
            desc = response.css('div.iiit-certification p::text').getall()
            for i in desc:
                re_description1 = re.sub('<(.*?)>','',i)
                re_description2 = re.sub('\s\s','',re_description1)
                re_description3 = re.sub('</(.*?)>','',re_description2)
                re_description = re_description3.replace('\t','').replace('\n','').replace('\r','')
                description += '<p>' + re_description + '</p>'
        
        if description == '':
            desc = response.css('div.col-md-9 div.col-md-7 p::text').getall()
            for i in desc:
                re_description1 = re.sub('<(.*?)>','',i)
                re_description2 = re.sub('\s\s','',re_description1)
                re_description3 = re.sub('</(.*?)>','',re_description2)
                re_description = re_description3.replace('\t','').replace('\n','').replace('\r','')
                description += '<p>' + re_description + '</p>'

        if description == '':
            desc = response.css('div.ehy-googlewe-grahp p::text').getall()
            for i in desc:
                re_description1 = re.sub('<(.*?)>','',i)
                re_description2 = re.sub('\s\s','',re_description1)
                re_description3 = re.sub('</(.*?)>','',re_description2)
                re_description = re_description3.replace('\t','').replace('\n','').replace('\r','')
                description += '<p>' + re_description + '</p>'
        
        if description == '':
            desc = response.css('div.col-md-7 p::text').getall()
            for i in desc:
                re_description1 = re.sub('<(.*?)>','',i)
                re_description2 = re.sub('\s\s','',re_description1)
                re_description3 = re.sub('</(.*?)>','',re_description2)
                re_description = re_description3.replace('\t','').replace('\n','').replace('\r','')
                description += '<p>' + re_description + '</p>'

        ## FEES 
        fee = ''
        fee = response.xpath('//table[@class="pricing-tab"]//tr[2]/td[2]/text()').get()
        
        f1 = ''
        if fee == ''or fee is None:
            fee = response.xpath('//div[@class="programfee-sec rt-bar"]//div[@class="col-md-6"][1]//ul//li[1]/text()[2]').get()
        
        if fee == '' or fee is None:
            fee = response.xpath('//table[@class="program-fee"]//tr[5]//td[3]/text()').get()
        
        if fee == '' or fee is None:
            fee =response.xpath('//div[@class="fee-sec"]//span/text()[2]').get()

        if fee == '' or fee is None:
            fee = response.xpath('//table[@class="pricing-tab"]//tr[4]//td[2]/text()').get()
        
        if fee == '\r\n                          ':
            fee = response.xpath('//table[@class="pricing-tab"]//tr[2]/td[2]/text()[2]').get()
        
        if fee == '' or fee is None:
            fee = response.xpath('//table[@class="pricing-tab"]//tr[3]/td[2]/text()').get()
            
        if fee == '' or fee is None:
            fee = response.xpath('//div[@class="fee-inner"]//ul//li[1]/text()[2]').get()

        if fee == '' or fee is None:
            fee = response.xpath('//table[@class="pricing-tab"]//td[2]/text()[2]').get()
        
        if fee == '' or fee is None:
            fee = response.xpath('//table[@class="table"]//tr[3]//td[2]/text()[2]').get()

        

        ## ELIGIBILITY
        
        eligibility = ''
        eligible = response.xpath('//div[@id="eligibility"]//ul/li/text()').getall()
        eligibility = '|'.join(eligible)
        
        if eligibility == '':
            eligible = response.xpath('//section[@class="eligibility"]//ul[@class="eligibility-list"]/li/text()').getall()
            eligibility = '|'.join(eligible)
        
        if eligibility == '':
            eligible = response.xpath('//div[@id ="eligibility"]//p/text()').getall()
            eligibility = '|'.join(eligible)
        
        if eligibility == '':
            eligible = response.xpath('//section[@class="eligibility-sec"]//ul[@class="eligibility"]//li/span/text()').getall()
            eligibility = '|'.join(eligible)
        
        if eligibility == '\r\n               |\r\n                  |\r\n                    |\r\n                    |\r\n                  ':
            eligible = response.xpath('//div[@id="eligibility"]//ul/li/strong/text()').getall()
            eligibility = '|'.join(eligible)
        
        if eligibility == '':
            eligible = response.xpath('//ul[@class="ideal-list one"]/li/text()').getall()
            eligibility = '|'.join(eligible)

        if eligibility == '':
            eligible = response.xpath('//div[@id="enrollmentProcess"]//p/text()').getall()
            eligibility = '|'.join(eligible)
        
        if eligibility == '':
            eligible = response.xpath('//ul[@class="admission-round"]/li/text()').getall()
            eligibility = '|'.join(eligible)
        
        if eligibility == '':
            eligible = response.xpath('//section[@id="Eligibility"]//p[2]/text()').getall()
            eligibility = '|'.join(eligible)
        
        if eligibility == '':
            eligible = response.xpath('//div[@id="enrollmentProcess"]//ul/li/text()').getall()
            eligibility = '|'.join(eligible)

        
        ## FACULTY
        instructor_names = ''
        instructor_designation = ''
        instructor_description = ''

        instruct_names = []
        instructor_name = response.xpath('//ul[@class="sub-faculty"]/li/h4/text()').getall()
        instructor_names = '|'.join(instructor_name)

        instructor_desig = response.xpath('//ul[@class="sub-faculty"]/li/p[1]/text()[1]').getall()
        instructor_designation = '|'.join(instructor_desig)

        instruct_desc = []
        instructor_desc = response.xpath('//ul[@class="sub-faculty"]/li/p[2]/text()').getall()
        for i in instructor_desc:
            if i!= '':
                re_desc = re.sub('\r\n\s*','',i)
                instruct_desc.append(re_desc)
        instructor_description = '|'.join(instruct_desc)
        
        if instructor_names == '':
            instructor_name = response.xpath('//section[@id="faculty"]//div[@class="col-md-3"]//a/text()').getall()
            for i in instructor_name:
                re_name = re.sub('\r\n\s*','',i)
                instruct_names.append(re_name)
            instructor_names = '|'.join(instruct_names)
        
        if instructor_description == '':
            instructor_desc = response.xpath('//section[@id="faculty"]//div[@class="col-md-3"]//div[@class="comment more"]/text() | //div[@class="col-md-3"]//div[@class="comment more"]//span[2]/span/text()').getall()
            for i in instructor_desc:
                if i!= '':
                    re_desc = re.sub('\r\n\s*','',i)
                    instruct_desc.append(re_desc)
            instructor_description = '|'.join(instruct_desc)

        if instructor_names == '':
            instructor_name = response.xpath('//div[@class="programme-directors-scroll"]/ul//span[@class="faculty-cnt"]//h4/text()').getall()
            for i in instructor_name:
                re_name = re.sub('\r\s*','',i).replace('\n','')
                instruct_names.append(re_name)
            instructor_names = '|'.join(instruct_names)
        
        desig = []
        if instructor_designation == '':
            instructor_desig = response.xpath('//div[@class="programme-directors-scroll"]/ul//span[@class="faculty-cnt"]//span/text()[1]').getall()
            for i in instructor_desig:
                re_desig = re.sub('\r\s*','',i).replace('\n','')
                desig.append(re_desig)       
            instructor_designation = '|'.join(desig)
        
        if instructor_description == '':
            instructor_desc = response.xpath('//div[@class="programme-directors-scroll"]/ul//span[@class="faculty-cnt"]//p/text()').getall()
            for i in instructor_desc:
                if i!= '':
                    re_desc = re.sub('\r\n\s*','',i)
                    instruct_desc.append(re_desc)
            instructor_description = '|'.join(instruct_desc)

        if instructor_names == '':
            instructor_name = response.xpath('//div[@id="advisory-committee"]//ul/li//h4/text()').getall()
            for i in instructor_name:
                re_name = re.sub('\r\s*','',i).replace('\n','')
                instruct_names.append(re_name)
            instructor_names = '|'.join(instruct_names)
        
        if instructor_designation == '':
            instructor_desig = response.xpath('//div[@id="advisory-committee"]//ul/li//h4/span/text()[1]').getall()
            instructor_designation = '|'.join(instructor_desig)
        
        if instructor_description == '':
            instructor_desc = response.xpath('//div[@id="advisory-committee"]//ul/li//div[2]/p/text()').getall()
            for i in instructor_desc:
                if i!= '':
                    re_desc = re.sub('\r\n\s*','',i)
                    instruct_desc.append(re_desc)
            instructor_description = '|'.join(instruct_desc)

        if instructor_names == '':
            instructor_name = response.xpath('//div[@class="panel panel-default faculty-collapse"]//a/text()[1]').getall()
            for i in instructor_name:
                re_name = re.sub('\r\s*','',i).replace('\n','')
                instruct_names.append(re_name)
            instructor_names = '|'.join(instruct_names)
        
        if instructor_designation == '':
            instructor_desig = response.xpath('//div[@class="panel panel-default faculty-collapse"]//div[2]//p[1]/text()[1]').getall()
            instructor_designation = '|'.join(instructor_desig)
        
        if instructor_description == '':
            instructor_desc = response.xpath('//div[@class="panel panel-default faculty-collapse"]//div[2]//p[2]/text()').getall()
            for i in instructor_desc:
                if i!= '':
                    re_desc = re.sub('\r\n\s*','',i)
                    instruct_desc.append(re_desc)
            instructor_description = '|'.join(instruct_desc)
        
        if instructor_names == '':
            instructor_name = response.xpath('//div[@id="faculty"]//ul/li//h4/text()').getall()
            for i in instructor_name:
                re_name = re.sub('\r\s*','',i).replace('\n','')
                instruct_names.append(re_name)
            instructor_names = '|'.join(instruct_names)
        
        if instructor_designation == '':
            instructor_desig = response.xpath('//div[@id="faculty"]//ul/li//span/text()').getall()
            instructor_designation = '|'.join(instructor_desig)
        
        if instructor_description == '':
            instructor_desc = response.xpath('//div[@id="faculty"]//ul/li//p/text()').getall()
            for i in instructor_desc:
                if i!= '':
                    re_desc = re.sub('\r\n\s*','',i)
                    instruct_desc.append(re_desc)
            instructor_description = '|'.join(instruct_desc)

        if instructor_names == '':
            instructor_name = response.xpath('//ul[@class="faculty-list"]/li/text()').getall()
            for i in instructor_name:
                re_name = re.sub('\r\s*','',i).replace('\n','')
                instruct_names.append(re_name)
            instructor_names = '|'.join(instruct_names)
        
        if instructor_designation == '':
            instructor_desig = response.xpath('//ul[@class="faculty-list"]/li/span[1]/text()[1]').getall()
            instructor_designation = '|'.join(instructor_desig)

        if instructor_description == '':
            instructor_desc = response.xpath('//ul[@class="faculty-list"]/li/span[2]/text()[1]').getall()
            for i in instructor_desc:
                if i!= '':
                    re_desc = re.sub('\r\n\s*','',i)
                    instruct_desc.append(re_desc)
            instructor_description = '|'.join(instruct_desc)
        
        if instructor_names == '':
            instructor_name = response.xpath('//section[@id="faculty"]//ul/li//h4/text()').getall()
            for i in instructor_name:
                re_name = re.sub('\r\s*','',i).replace('\n','')
                instruct_names.append(re_name)
            instructor_names = '|'.join(instruct_names)

        if instructor_desc == '':
            instructor_desc = response.xpath('//section[@id="faculty"]//ul/li/div[2]/p/text()').getall()
            for i in instructor_desc:
                if i!= '':
                    re_desc = re.sub('\r\n\s*','',i)
                    instruct_desc.append(re_desc)
            instructor_description = '|'.join(instruct_desc)
        
        if instructor_names == '':
            instructor_name = response.xpath('//section[@class="the-faculty"]//div[@class="swiper-wrapper"]//div/h3/text()').getall()
            for i in instructor_name:
                re_name = re.sub('\r\s*','',i).replace('\n','')
                instruct_names.append(re_name)
            instructor_names = '|'.join(instruct_names)

        if instructor_designation == '':
            instructor_desig = response.xpath('//section[@class="the-faculty"]//div[@class="swiper-wrapper"]//div/h3/span/text()').getall()
            instructor_designation = '|'.join(instructor_desig)
        
        if instructor_description == '':
            instructor_desc = response.xpath('//section[@class="the-faculty"]//div[@class="swiper-wrapper"]//div/p/text()').getall()
            for i in instructor_desc:
                if i!= '':
                    re_desc = re.sub('\r\n\s*','',i)
                    instruct_desc.append(re_desc)
            instructor_description = '|'.join(instruct_desc)
        
        if instructor_names == '':
            instructor_name = response.xpath('//ul[@class="list-inline faculty-div"]/li//h3/text()').getall()
            for i in instructor_name:
                re_name = re.sub('\r\s*','',i).replace('\n','')
                instruct_names.append(re_name)
            instructor_names = '|'.join(instruct_names)
        
        if instructor_designation == '':
            instructor_desig = response.xpath('//ul[@class="list-inline faculty-div"]/li//p/text()').getall()
            instructor_designation = '|'.join(instructor_desig)

        if instructor_description == '':
            instructor_desc = response.xpath('//div[@class="carousel-inner"]//ul').getall()
            for i in instructor_desc:
                instruct_desc.append(i.replace('<li>','').replace('</li>'))
            instructor_description = '|'.join(instruct_desc)

        
        
        
        ## CURRICULUM
        cur = ''
        mods = response.css('div.curriculum-box div.panel-group h4::text').getall()
        mod = []
        submod = []
        for i in mods:
            if i == '\n                    ' or i == '\r  ' or i == ' ' or i == '  ' or i == '\n' or i == '\n ':
                continue
            else:
                re_mod1 = re.sub('\s\s','',i)
                re_mod2 = re.sub(r'<img(.*?)>','',re_mod1)
                re_mod3 = re.sub(r'<(.*?)>','',re_mod2)
                re_mod4 = re.sub(r'</(.*?)>','',re_mod3)
                re_mod = re_mod4.replace('\t','').replace('\n','').replace('\r','')

                mod.append(re_mod)

        sub = response.css('div.curriculum-box div.panel-group div.panel-body ul').getall()
        for i in sub:
            re_submod1 = re.sub('\s\s','',i)
            re_submod2 = re.sub(r'<img(.*?)>','',re_submod1)
            re_submod3 = re.sub(r'<(.*?)>','',re_submod2)
            re_submod4 = re.sub(r'</(.*?)>','',re_submod3)
            re_submod = re_submod4.replace('\t','').replace('\n','').replace('\r','')

            submod.append(re_submod)

        if mod == []:
            mods = response.css('div.curriculum-box div.moduls div.col-md-6 h4::text').getall()
            for i in mods:
                re_mod1 = re.sub('\s\s','',i)
                re_mod2 = re.sub(r'<img(.*?)>','',re_mod1)
                re_mod3 = re.sub(r'<(.*?)>','',re_mod2)
                re_mod4 = re.sub(r'</(.*?)>','',re_mod3)
                re_mod = re_mod4.replace('\t','').replace('\n','').replace('\r','')

                mod.append(re_mod)

        if submod == []:
            sub = response.css('div.curriculum-box div.moduls div.modules-inner div.col-md-6 ul').getall()
            for i in sub:
                re_submod1 = re.sub('\s\s','',i)
                re_submod2 = re.sub(r'<img(.*?)>','',re_submod1)
                re_submod3 = re.sub(r'<(.*?)>','',re_submod2)
                re_submod4 = re.sub(r'</(.*?)>','',re_submod3)
                re_submod = re_submod4.replace('\t','').replace('\n','').replace('\r','')
                
                submod.append(re_submod)

        if mod == []:
            mods = response.css('div.curriculum-sec div.panel-group h4::text').getall()
            mod = []
            for i in mods:
                if i == '\n                    ' or i == '\r  ' or i == ' ' or i == '  ' or i == '\n' or i == '\n ':
                    continue
                else:
                    re_mod1 = re.sub('\s\s','',i)
                    re_mod2 = re.sub(r'<img(.*?)>','',re_mod1)
                    re_mod3 = re.sub(r'<(.*?)>','',re_mod2)
                    re_mod4 = re.sub(r'</(.*?)>','',re_mod3)
                    re_mod = re_mod4.replace('\t','').replace('\n','').replace('\r','')

                    mod.append(re_mod)

        if submod == []:
            sub = response.css('div.curriculum-sec div.panel-group div.panel-body ul').getall()
            for i in sub:
                re_submod1 = re.sub('\s\s','',i)
                re_submod2 = re.sub(r'<img(.*?)>','',re_submod1)
                re_submod3 = re.sub(r'<(.*?)>','',re_submod2)
                re_submod4 = re.sub(r'</(.*?)>','',re_submod3)
                re_submod = re_submod4.replace('\t','').replace('\n','').replace('\r','')

                submod.append(re_submod)
        
        if mod == []:
            mods = response.css('div.curriculum-sec div.panel-group div.panel-heading a::text').getall()
            mod = []
            for i in mods:
                if i == '\n                    ' or i == '\r  ' or i == ' ' or i == '  ' or i == '\n' or i == '\n ':
                    continue
                else:
                    re_mod1 = re.sub('\s\s','',i)
                    re_mod2 = re.sub(r'<img(.*?)>','',re_mod1)
                    re_mod3 = re.sub(r'<(.*?)>','',re_mod2)
                    re_mod4 = re.sub(r'</(.*?)>','',re_mod3)
                    re_mod = re_mod4.replace('\t','').replace('\n','').replace('\r','')

                    mod.append(re_mod)
                    
        if submod == []:
            sub = response.css('div.panel-curriculum-sec div.panel-group div.panel-collapse div.curriculum-box').getall()
            for i in sub:
                re_submod1 = re.sub('\s\s','',i)
                re_submod2 = re.sub(r'<img(.*?)>','',re_submod1)
                re_submod3 = re.sub(r'<(.*?)>','',re_submod2)
                re_submod4 = re.sub(r'</(.*?)>','',re_submod3)
                re_submod = re_submod4.replace('\t','').replace('\n','').replace('\r','')

                submod.append(re_submod)

        if mod == []:
            mods = response.css('ul.real-world-curriculum li::text').getall()
            mod = []
            for i in mods:
                if i == '\n                    ' or i == '\r  ' or i == ' ' or i == '  ' or i == '\n' or i == '\n ' or i == '\n\t\t\t\t\t\t\t':
                    continue
                else:
                    re_mod1 = re.sub('\s\s','',i)
                    re_mod2 = re.sub(r'<img(.*?)>','',re_mod1)
                    re_mod3 = re.sub(r'<(.*?)>','',re_mod2)
                    re_mod4 = re.sub(r'</(.*?)>','',re_mod3)
                    re_mod = re_mod4.replace('\t','').replace('\n','').replace('\r','')

                    mod.append(re_mod)

        if mod == []:
            mods = response.css('ul.modules-list li').getall()
            mod = []
            for i in mods:
                if i == '\n                    ' or i == '\r  ' or i == ' ' or i == '  ' or i == '\n' or i == '\n ' or i == '\n\t\t\t\t\t\t\t':
                    continue
                else:
                    re_mod1 = re.sub('\s\s','',i)
                    re_mod2 = re.sub(r'<img(.*?)>','',re_mod1)
                    re_mod3 = re.sub(r'<(.*?)>','',re_mod2)
                    re_mod4 = re.sub(r'</(.*?)>','',re_mod3)
                    re_mod = re_mod4.replace('\t','').replace('\n','').replace('\r','')

                    mod.append(re_mod)

        if mod == []:
            mods = response.css('div.modules-accordiaon div.card-body li').getall()
            mod = []
            for i in mods:
                if i == '\n                    ' or i == '\r  ' or i == ' ' or i == '  ' or i == '\n' or i == '\n ' or i == '\n\t\t\t\t\t\t\t':
                    continue
                else:
                    re_mod1 = re.sub('\s\s','',i)
                    re_mod2 = re.sub(r'<img(.*?)>','',re_mod1)
                    re_mod3 = re.sub(r'<(.*?)>','',re_mod2)
                    re_mod4 = re.sub(r'</(.*?)>','',re_mod3)
                    re_mod = re_mod4.replace('\t','').replace('\n','').replace('\r','')

                    mod.append(re_mod)
        
        if mod == []:
            mods = response.css('div.curriculum-sec div.prg-schedule ul').getall()
            mod = []
            for i in mods:
                if i == '\n                    ' or i == '\r  ' or i == ' ' or i == '  ' or i == '\n' or i == '\n ' or i == '\n\t\t\t\t\t\t\t':
                    continue
                else:
                    re_mod1 = re.sub('\s\s','',i)
                    re_mod2 = re.sub(r'<img(.*?)>','',re_mod1)
                    re_mod3 = re.sub(r'<(.*?)>','',re_mod2)
                    re_mod4 = re.sub(r'</(.*?)>','',re_mod3)
                    re_mod = re_mod4.replace('\t','').replace('\n','').replace('\r','')

                    mod.append(re_mod)

        if mod == []:
            mods = response.css('div.accordion-item h2 button::text').getall()
            for i in mods:
                if i == '\n                    ' or i == '\r  ' or i == ' ' or i == '  ' or i == '\n' or i == '\n ' or i == '\n\t\t\t\t\t\t\t':
                    continue
                else:
                    re_mod1 = re.sub('\s\s','',i)
                    re_mod2 = re.sub(r'<img(.*?)>','',re_mod1)
                    re_mod3 = re.sub(r'<(.*?)>','',re_mod2)
                    re_mod4 = re.sub(r'</(.*?)>','',re_mod3)
                    re_mod = re_mod4.replace('\t','').replace('\n','').replace('\r','')

                    mod.append(re_mod)
        
        if submod == []:
            sub = response.css('div.accordion-item div.accordion-body div.col-10').getall()
            for i in sub:
                re_submod1 = re.sub('\s\s','',i)
                re_submod2 = re.sub(r'<img(.*?)>','',re_submod1)
                re_submod3 = re.sub(r'<(.*?)>','',re_submod2)
                re_submod4 = re.sub(r'</(.*?)>','',re_submod3)
                re_submod = re_submod4.replace('\t','').replace('\n','').replace('\r','')

                submod.append(re_submod)

        if mod == []:
            mods = response.css('div.prg-format ul.program-highlight li div.curriculum-highlights').getall()
            for i in mods:
                if i == '\n                    ' or i == '\r  ' or i == ' ' or i == '  ' or i == '\n' or i == '\n ' or i == '\n\t\t\t\t\t\t\t':
                    continue
                else:
                    re_mod1 = re.sub('\s\s','',i)
                    re_mod2 = re.sub(r'<img(.*?)>','',re_mod1)
                    re_mod3 = re.sub(r'<(.*?)>','',re_mod2)
                    re_mod4 = re.sub(r'</(.*?)>','',re_mod3)
                    re_mod = re_mod4.replace('\t','').replace('\n','').replace('\r','')

                    mod.append(re_mod)

        if mod == []:
            mods = response.css('div.col-md-12 ul.certificate-curriculum li').getall()
            for i in mods:
                if i == '\n                    ' or i == '\r  ' or i == ' ' or i == '  ' or i == '\n' or i == '\n ' or i == '\n\t\t\t\t\t\t\t':
                    continue
                else:
                    re_mod1 = re.sub('\s\s','',i)
                    re_mod2 = re.sub(r'<img(.*?)>','',re_mod1)
                    re_mod3 = re.sub(r'<(.*?)>','',re_mod2)
                    re_mod4 = re.sub(r'</(.*?)>','',re_mod3)
                    re_mod = re_mod4.replace('\t','').replace('\n','').replace('\r','')

                    mod.append(re_mod)
        
        if mod == []:
            mods = response.css('div.card div.card-header h2 button::text').getall()
            for i in mods:
                if i == '\n                    ' or i == '\r  ' or i == ' ' or i == '  ' or i == '   ' or i == '\n' or i == '\n ' or i == '\n\t\t\t\t\t\t\t':
                    continue
                else:
                    re_mod1 = re.sub('\s\s','',i)
                    re_mod2 = re.sub(r'<img(.*?)>','',re_mod1)
                    re_mod3 = re.sub(r'<(.*?)>','',re_mod2)
                    re_mod4 = re.sub(r'</(.*?)>','',re_mod3)
                    re_mod = re_mod4.replace('\t','').replace('\n','').replace('\r','')

                    mod.append(re_mod)
        
        if submod == []:
            sub = response.css('div.collapse div.card-body div.card h2 button').getall()
            for i in sub:
                re_submod1 = re.sub('\s\s','',i)
                re_submod2 = re.sub(r'<img(.*?)>','',re_submod1)
                re_submod3 = re.sub(r'<(.*?)>','',re_submod2)
                re_submod4 = re.sub(r'</(.*?)>','',re_submod3)
                re_submod = re_submod4.replace('\t','').replace('\n','').replace('\r','')

                submod.append(re_submod)
        
        if mod == []:
            mods = response.css('div.moduls div.modules-inner h3::text').getall()
            for i in mods:
                if i == '\n                    ' or i == '\r  ' or i == ' ' or i == '  ' or i == '   ' or i == '\n' or i == '\n ' or i == '\n\t\t\t\t\t\t\t':
                    continue
                else:
                    re_mod1 = re.sub('\s\s','',i)
                    re_mod2 = re.sub(r'<img(.*?)>','',re_mod1)
                    re_mod3 = re.sub(r'<(.*?)>','',re_mod2)
                    re_mod4 = re.sub(r'</(.*?)>','',re_mod3)
                    re_mod = re_mod4.replace('\t','').replace('\n','').replace('\r','')

                    mod.append(re_mod)
        
        if submod == []:
            sub = response.css('div.moduls div.modules-inner ul').getall()
            for i in sub:
                re_submod1 = re.sub('\s\s','',i)
                re_submod2 = re.sub(r'<img(.*?)>','',re_submod1)
                re_submod3 = re.sub(r'<(.*?)>','',re_submod2)
                re_submod4 = re.sub(r'</(.*?)>','',re_submod3)
                re_submod = re_submod4.replace('\t','').replace('\n','').replace('\r','')

                submod.append(re_submod)

        if mod == []:
            mods = response.css('div.curriculum-box ul.capstone-projects li::text').getall()
            for i in mods:
                if i == '\n                    ' or i == '\r  ' or i == ' ' or i == '  ' or i == '   ' or i == '\n' or i == '\n ' or i == '\n\t\t\t\t\t\t\t':
                    continue
                else:
                    re_mod1 = re.sub('\s\s','',i)
                    re_mod2 = re.sub(r'<img(.*?)>','',re_mod1)
                    re_mod3 = re.sub(r'<(.*?)>','',re_mod2)
                    re_mod4 = re.sub(r'</(.*?)>','',re_mod3)
                    re_mod = re.sub(r'\(.*?)','',re_mod4)

                    mod.append(re_mod)

        if mod == []:
            mods = response.css('div.curriculum-box div.panel-group div.panel div.panel-heading h4::text').getall()
            for i in mods:
                if i == '\n                    ' or i == '\r  ' or i == ' ' or i == '  ' or i == '   ' or i == '\n' or i == '\n ' or i == '\n\t\t\t\t\t\t\t':
                    continue
                else:
                    re_mod1 = re.sub('\s\s','',i)
                    re_mod2 = re.sub(r'<img(.*?)>','',re_mod1)
                    re_mod3 = re.sub(r'<(.*?)>','',re_mod2)
                    re_mod4 = re.sub(r'</(.*?)>','',re_mod3)
                    re_mod = re_mod4.replace('\t','').replace('\n','').replace('\r','')

                    mod.append(re_mod)
        
        if sub == []:
            submod = response.css('div.curriculum-box div.panel-group div.panel div.panel-collapse div.panel-body ul').getall()
            for i in sub:
                re_submod1 = re.sub('\s\s','',i)
                re_submod2 = re.sub(r'<img(.*?)>','',re_submod1)
                re_submod3 = re.sub(r'<(.*?)>','',re_submod2)
                re_submod4 = re.sub(r'</(.*?)>','',re_submod3)
                re_submod = re_submod4.replace('\t','').replace('\n','').replace('\r','')

                submod.append(re_submod)
        
        if mod == []:
            mods = response.css('div.curriculum-sec ul.curriculum-modules li::text').getall()
            for i in mods:
                if i == '\n                    ' or i == '\r  ' or i == ' ' or i == '  ' or i == '   ' or i == '\n' or i == '\n ' or i == '\n\t\t\t\t\t\t\t':
                    continue
                else:
                    re_mod1 = re.sub('\s\s','',i)
                    re_mod2 = re.sub(r'<img(.*?)>','',re_mod1)
                    re_mod3 = re.sub(r'<(.*?)>','',re_mod2)
                    re_mod4 = re.sub(r'</(.*?)>','',re_mod3)
                    re_mod = re_mod4.replace('\t','').replace('\n','').replace('\r','')

                    mod.append(re_mod)
        
        if sub == []:
            submod = response.css('div.curriculum-sec ul.curriculum-modules li p').getall()
            for i in sub:
                re_submod1 = re.sub('\s\s','',i)
                re_submod2 = re.sub(r'<img(.*?)>','',re_submod1)
                re_submod3 = re.sub(r'<(.*?)>','',re_submod2)
                re_submod4 = re.sub(r'</(.*?)>','',re_submod3)
                re_submod = re_submod4.replace('\t','').replace('\n','').replace('\r','')

                submod.append(re_submod)
              
        
        ##### Integrate modules and submodules
        modules = ''
        module_list = ''
        if mod != [] and sub != []:
            s1 = '<?xml version="1.0"?><mainmodule>' 
            s2 = '</mainmodule>'
            module_list = ''
            f = ''
            f1 = ''
            for i,j,m in zip(mod,submod,range(1,len(mod)+1)):
                if i == '' or i == ' ' or i == '  ' or i == '   ':
                    continue
                else:
                    modules = f'<heading>{i}</heading><subheading>'
                    i1 = ''
                    for l in range(1,len(submod)+1):
                        c = submod[l-1]
                        i = f'<item{l}>{c}</item{l}>'
                        i1 += i
                    s = ''
                    s += f'<module{m}>' + modules + i1 + '</subheading>' + f'</module{m}>'
                    f += s
            module_list = s1 + f + s2
    
        elif mod != [] and submod == []:
            for i in range(len(mod)):
                if mod[i] == '' or mod[i] == ' ' or mod[i] == '  ' or mod[i] == '   ':
                    continue
                else:
                    # <p><strong>Module {modulenum}: module_text</strong></p>
                    module_list += f'<p><strong>Module {i+1}: {mod[i]}</strong></p>'
    
        ## FAQS
        faq_questions = ''
        faq_answers = ''

        questions = []
        faq_ques = response.xpath('//div[@id="faq"]//div[@class="panel panel-default" and position()>1]//h4/a/text()').getall()
        for i in faq_ques:
            re_ques1 = re.sub('\s\s','',i)
            re_ques2 = re.sub('\r','',re_ques1)
            re_ques = re.sub('\n','',re_ques2)
            questions.append(re_ques)
        faq_questions = '|'.join(questions)

        answers = []
        faq_ans = response.xpath('//div[@id="faq"]//div[@class="panel panel-default" and position()>1]//div[2]//p | //div[@id="faq"]//div[@class="panel panel-default" and position()>1]//div[2]//ul').getall()
        for i in faq_ans:
            re_ans1 = re.sub('\s\s','',i)
            re_ans2 = re.sub(r'<(.*?)>','',re_ans1)
            re_ans3 = re.sub(r'</(.*?)>','',re_ans2)
            re_ans = re.sub('\n\s\s','',re_ans3)
            answers.append(re_ans)
        faq_answers = '|'.join(answers)

        if faq_questions == '':
            faq_ques = response.xpath('//section[@id="faq"]//div[@class="card"]//h5/a/text()').getall()
            for i in faq_ques:
                re_ques1 = re.sub('\s\s','',i)
                re_ques2 = re.sub('\r','',re_ques1)
                re_ques = re.sub('\n','',re_ques2)
                questions.append(re_ques)
            faq_questions = '|'.join(questions)
        
        if faq_answers == '':
            faq_ans = response.xpath('//section[@id="faq"]//div[@class="card"]//div[2]//p').getall()
            for i in faq_ans:
                re_ans1 = re.sub('\s\s','',i)
                re_ans2 = re.sub(r'<(.*?)>','',re_ans1)
                re_ans3 = re.sub(r'</(.*?)>','',re_ans2)
                re_ans = re.sub('\n\s\s','',re_ans3)
                answers.append(re_ans)
            faq_answers = '|'.join(answers)
        
        if faq_questions == '':
            faq_ques = response.xpath('//section[@id="faq"]//div[@class="card"]//h5/button/text()').getall()
            for i in faq_ques:
                re_ques1 = re.sub('\s\s','',i)
                re_ques2 = re.sub('\r','',re_ques1)
                re_ques = re.sub('\n','',re_ques2)
                questions.append(re_ques)
            faq_questions = '|'.join(questions)
        
        if faq_answers == '':
            faq_ans = response.xpath('//section[@id="faq"]//div[@id="accordion"]//div[@class="card-body"]').getall()
            for i in faq_ans:
                re_ans1 = re.sub('\s\s','',i)
                re_ans2 = re.sub(r'<(.*?)>','',re_ans1)
                re_ans3 = re.sub(r'</(.*?)>','',re_ans2)
                re_ans = re.sub('\n\s\s','',re_ans3)
                answers.append(re_ans)
        faq_answers = '|'.join(answers)

        if faq_questions == '':
            faq_ques = response.xpath('//section[@id="faq"]//div[@class="accordion-item"]//h2/button/text()').getall()
            for i in faq_ques:
                re_ques1 = re.sub('\s\s','',i)
                re_ques2 = re.sub('\r','',re_ques1)
                re_ques = re.sub('\n','',re_ques2)
                questions.append(re_ques)
            faq_questions = '|'.join(questions)
        
        if faq_answers == '':
            faq_ans = response.xpath('//section[@id="faq"]//div[@class="accordion-item"]//div[@class="accordion-collapse collapse"]//p | //section[@id="faq"]//div[@class="accordion-item"]//div[@class="accordion-collapse collapse"]//ul').getall()
            for i in faq_ans:
                re_ans1 = re.sub('\s\s','',i)
                re_ans2 = re.sub(r'<(.*?)>','',re_ans1)
                re_ans3 = re.sub(r'</(.*?)>','',re_ans2)
                re_ans = re.sub('\n\s\s','',re_ans3)
                answers.append(re_ans)
        faq_answers = '|'.join(answers)
        

        ## ALUMNIS
        reviewer_name = ''
        reviewer_desig = ''
        reviewer_desc = ''
        reviewer_image = ''

        review_name = []
        alumni_name = response.css('section.alumni ul.alumni-testimonials li span small::text').getall()
        for i in alumni_name:
            re_name1 = re.sub('\s\s','',i)
            re_name2 = re.sub('\r','',re_name1)
            re_name3 = re.sub('\n','',re_name2)
            re_name = re.sub('\t\t','',re_name3)
            review_name.append(re_name)
        reviewer_name = '|'.join(review_name)
        
        alumni_desig = response.css('section.alumni ul.alumni-testimonials li span::text').getall()
        reviewer_desig = '|'.join(alumni_desig)
        
        review_desc = []
        alumni_desc = response.css('section.alumni ul.alumni-testimonials li::text').getall()
        for i in alumni_desc:
            re_desc1 = re.sub('\s\s','',i)
            re_desc = re.sub('\n','',re_desc1)
            review_desc.append(re_desc)
        reviewer_desc = '|'.join(review_desc)
        
        review_img = []
        alumni_img = response.css('section.alumni ul.alumni-testimonials li img').getall()
        for i in alumni_img:
            re_img = re.sub(r'<(.*?)>]','',i)
            review_img.append(re_img) 
        reviewer_image = '|'.join(review_img)
        
        if reviewer_name == '':
            alumni_name = response.css('div.sop-feedback ul li span strong::text').getall()
            for i in alumni_name:
                re_name1 = re.sub('\s\s','',i)
                re_name2 = re.sub('\r','',re_name1)
                re_name3 = re.sub('\n','',re_name2)
                re_name = re.sub('\t\t','',re_name3)
                review_name.append(re_name)
            reviewer_name = '|'.join(review_name)
       
        if reviewer_desc == '':
            alumni_desc = response.css('div.sop-feedback ul li::text').getall()
            for i in alumni_desc:
                re_desc1 = re.sub('\s\s','',i)
                re_desc = re.sub('\n','',re_desc1)
                review_desc.append(re_desc)
            reviewer_desc = '|'.join(review_desc)
        
        if reviewer_desc == '':
            alumni_desc = response.css('section.testinonials-sec div.item div.testimonialss-inner h3::text').getall()
            for i in alumni_desc:
                re_desc1 = re.sub('\s\s','',i)
                re_desc = re.sub('\n','',re_desc1)
                review_desc.append(re_desc)
            reviewer_desc = '|'.join(review_desc)
        
        if reviewer_image:
            alumni_img = response.css('section.testimonials-sec div.item div.testimonialss-inner img').getall()
            for i in alumni_img:
                re_img = re.sub(r'<(.*?)>]','',i)
                review_img.append(re_img) 
            reviewer_image = '|'.join(review_img)
        
        if reviewer_name == '':
            alumni_name = response.css('div.sop-feedback div.carousel-inner div.col-md-4 p strong::text').getall()
            for i in alumni_name:
                re_name1 = re.sub('\s\s','',i)
                re_name2 = re.sub('\r','',re_name1)
                re_name3 = re.sub('\n','',re_name2)
                re_name = re.sub('\t\t','',re_name3)
                review_name.append(re_name)
            reviewer_name = '|'.join(review_name)
        
        if reviewer_desc == '':
            alumni_desc = response.css('div.sop-feedback div.carousel-inner div.col-md-4 div.quotesec p::text').getall()
            for i in alumni_desc:
                re_desc1 = re.sub('\s\s','',i)
                re_desc = re.sub('\n','',re_desc1)
                review_desc.append(re_desc)
            reviewer_desc = '|'.join(review_desc)

        if reviewer_name == '':
            alumni_name = response.css('div.col-md-8 div.quote-sec span strong::text').getall()
            for i in alumni_name:
                re_name1 = re.sub('\s\s','',i)
                re_name2 = re.sub('\r','',re_name1)
                re_name3 = re.sub('\n','',re_name2)
                re_name = re.sub('\t\t','',re_name3)
                review_name.append(re_name)
            reviewer_name = '|'.join(review_name)
        
        if reviewer_desc == '':
            alumni_desc = response.css('div.col-md-8 div.quote-sec p::text').getall()
            for i in alumni_desc:
                re_desc1 = re.sub('\s\s','',i)
                re_desc = re.sub('\n','',re_desc1)
                review_desc.append(re_desc)
            reviewer_desc = '|'.join(review_desc)

        if reviewer_name == '':
            alumni_name = response.css('section.transformational-experience div.swiper-wrapper p::text').getall()
            for i in alumni_name:
                re_name1 = re.sub('\s\s','',i)
                re_name2 = re.sub('\r','',re_name1)
                re_name3 = re.sub('\n','',re_name2)
                re_name = re.sub('\t\t','',re_name3)
                review_name.append(re_name)
            reviewer_name = '|'.join(review_name)
        
        review_desig = []
        if reviewer_desig == '':
            alumni_desig = response.css('section.transformational-experience div.swiper-wrapper p span::text').getall()
            for i in alumni_desig:
                review_desig.append(i.replace('\r','').replace('\n',''))
            reviewer_desig = '|'.join(review_desig)
        
        if reviewer_desc == '':
            alumni_desc = response.css('section.transformational-experience div.swiper-wrapper div.prof-testimonial p::text').getall()
            for i in alumni_desc:
                re_desc1 = re.sub('\s\s','',i)
                re_desc = re.sub('\n','',re_desc1)
                review_desc.append(re_desc)
            reviewer_desc = '|'.join(review_desc)
        
        if reviewer_name == '':
            alumni_name = response.css('div.carousel.slide div.carousel-inner div.item li span::text').getall()
            for i in alumni_name:
                re_name1 = re.sub('\s\s','',i)
                re_name2 = re.sub('\r','',re_name1)
                re_name3 = re.sub('\n','',re_name2)
                re_name = re.sub('\t\t','',re_name3)
                review_name.append(re_name)
            reviewer_name = '|'.join(review_name)
        
        if reviewer_desig == '':
            alumni_desig = response.css('div.carousel.slide div.carousel-inner div.item li small::text').getall()
            for i in alumni_desig:
                review_desig.append(i.replace('\r','').replace('\n',''))
            reviewer_desig = '|'.join(review_desig)
        
        if reviewer_desc == '':
            alumni_desc = response.css('div.carousel.slide div.carousel-inner div.item li::text').getall()
            for i in alumni_desc:
                re_desc1 = re.sub('\s\s','',i)
                re_desc = re.sub('\n','',re_desc1)
                review_desc.append(re_desc)
            reviewer_desc = '|'.join(review_desc)
        
        if reviewer_name == '':
            alumni_name = response.css('div.col-md-8 div.quote-sec div.quote-single span::text').getall()
            for i in alumni_name:
                re_name1 = re.sub('\s\s','',i)
                re_name2 = re.sub('\r','',re_name1)
                re_name3 = re.sub('\n','',re_name2)
                re_name = re.sub('\t\t','',re_name3)
                review_name.append(re_name)
            reviewer_name = '|'.join(review_name)
        
        if reviewer_desc == '':
            alumni_desc = response.css('div.col-md-8 div.quote-sec div.quote-single p::text').getall()
            for i in alumni_desc:
                re_desc1 = re.sub('\s\s','',i)
                re_desc = re.sub('\n','',re_desc1)
                review_desc.append(re_desc)
            reviewer_desc = '|'.join(review_desc)    
        
        if reviewer_desig == '':
            alumni_desig = response.css('div.col-md-8 div.quote-sec div.quote-single span span::text').getall()
            for i in alumni_desig:
                review_desig.append(i.replace('\r','').replace('\n',''))
            reviewer_desig = '|'.join(review_desig)
        
        if reviewer_name == '':
            alumni_name = response.css('section.testimonials div.col-md-9 ul li span strong::text').getall()
            for i in alumni_name:
                re_name1 = re.sub('\s\s','',i)
                re_name2 = re.sub('\r','',re_name1)
                re_name3 = re.sub('\n','',re_name2)
                re_name = re.sub('\t\t','',re_name3)
                review_name.append(re_name)
            reviewer_name = '|'.join(review_name)
        
        if reviewer_image == '':
            alumni_img = response.css('section.testimonials div.col-md-9 ul li img').getall()
            for i in alumni_img:
                reviewer_img += i.replace('<','').replace('img src','').replace('=','').replace('>','').replace('alt','') + '|'
        
        if reviewer_desig == '':
            alumni_desig = response.css('section.testimonials div.col-md-9 ul li span::text').getall()
            for i in alumni_desig:
                review_desig.append(i.replace('\r','').replace('\n',''))
            reviewer_desig = '|'.join(review_desig)
        
        if reviewer_desc == '':
            alumni_desc = response.css('section.testimonials div.col-md-9 ul li::text').getall()
            for i in alumni_desc:
                re_desc1 = re.sub('\s\s','',i)
                re_desc = re.sub('\n','',re_desc1)
                review_desc.append(re_desc)
            reviewer_desc = '|'.join(review_desc)

        yield{
            'title': title1,
            'Description' : description,
            'start_date' : start_date,
            'course_duration' : duration,
            'price' : fee,
            'eligibility' : eligibility,
            'instructor_name' : instructor_names,
            'instructor_designation' : instructor_designation,
            'instructor_description' : instructor_description,
            'content_module' : module_list,
            'reviewer_name' : reviewer_name,
            'reviewer_image' : reviewer_image,
            'reviewer_desig' : reviewer_desig,
            'reviewer_desc' : reviewer_desc,
            'FAQ' : faq_questions,
            'FAQ_answers' : faq_answers
        }